---
title: "Awards & Honors "
subtitle: "Recognitions, Scholarships, and Distinctions"
title-block-banner: false
page-layout: full
---

### Invited Talks
-**Invited Student Panelist, American Statistical Association Joint Statistical Meetings Diversity Workshop and Mentoring Program, "Internships, Research Experiences, and Building Your Portfolio," Joint Statistical Meetings, Boston, MA (2026).**

## 2026
- **American Statistical Association Joint Statistical Meetings Early Career Travel Award (2026)**
- **American Statistical Association Joint Statistical Meetings Diversity Workshop and Mentoring Program Scholar (2026)**
- **Junior Scholar Fellow, South Carolina SmartState Center for Healthcare Quality, University of South Carolina (2026–2027)**
- **International Biometric Society Eastern North American Region (ENAR) DataFest 2026 Winner – Presidential Award Recipient, March 17, 2026**
- **Best Abstract Presentation Award, 7th National Big Data Health Science Conference (2026)**
- **Arnold School Dean’s Research Travel Award, Arnold School of Public Health, University of South Carolina (2026)**
## 2025
- **Arnold School Dean’s Research Travel Award, Arnold School of Public Health, University of South Carolina (2025)**

- **PharmaSUG 2025 Conference Travel Grant** – *Western Michigan University*  
  Awarded a conference travel grant of $1,000 to attend PharmaSUG 2025 in San Diego, recognizing excellence in clinical research and statistical programming.


- **PharmaSUG 2025 Student Scholarship** – *June 2025*. Recipient of a competitive award recognizing outstanding potential in clinical research and statistical programming across the entire US.



## 2024
- **Gerald Sievers Memorial Scholarship** – *May 2024*. \$2,000 merit-based scholarship awarded to the most outstanding statistics graduate student at Western Michigan University.

- **ASA Diversity Mentoring Program Scholar** – *2024*. Selected for a national program supporting underrepresented students in statistics through mentorship and career development. \$800.



## 2023
- **Best Teaching Assistant Award**, University of Ghana – *June 2023*. Honored by the School of Mathematical Sciences for exceptional commitment to undergraduate instruction and mentoring. Selected as top-performing TA out of 20+ departmental TAs


## 2022
- **Certification of Honor**  
  *University of Ghana Actuarial and Statistics Society* — Honored for tremendous service and commitment through 2 years of effective transformative leadership as Deputy Project and Program Head.


## 2018
- **Ghana National Petroleum Corporation STEM Scholarship Recipient** – *2018–2022*. Fully funded four-year national scholarship awarded to top STEM students in Ghana. First year: Gh9,000 and Gh7000 for the remaining 3-years.

## 2017
- **Best Economics Student**, WASSCE 2017 – *ADA Senior H.T School*. Graduated with distinction in Economics, recognized as the highest-performing student in the subject across the school cohort.

## 2015
- **Less Endowed Scholar 2015- 2017**,  – *ADA Senior H.T School*. A tuition scholarship awarded to the top 3 students in each department school-wide. Recognized among the top 3 in the Business Department.


## Volunteer
- **Volunteer Judge**, 7th National Big Data Health Conference – *Feb 2026*. Oversaw a clinical Data Analysis Datafest.

- **Volunteer Judge**, PharmaSUG 2025 – *Feb 2025*. Reviewed statistical research presentations for clarity, rigor, and innovation in clinical trial applications.

- **Planning Committee Member**, ASA StatFest – *2023–Present*. Helped organize national outreach events promoting statistics among underrepresented communities.


- **Academic Integrity Committee Representative** Western Michigan University-*2024-2025*
Promoted academic integrity by reviewing cases and setting standards for student across the University

- **Emergency Team Leader**- International Student Week Celebration, Western Michigan University-*Oct 2023* 
Led emergency response planning to ensure event safety
