---
title: "Publications & Conferences"
author: "Josh T.K"
---

## Manuscript Under Review

**[1.Kubuafor, E., Korley, J.T*._, et al. (2024). Evaluation of Time Series Forecasting Models for Predicting Lung Cancer Mortality Rates in the United States: A Comparison with Altuhaifa (2023) Study.Proceedings of the Mediterranean Life Sciences Union Annual Meeting (MEDLIFE-24), Istanbul, Turkey, 08-10 December 2024. *Springer Proceedings in Mathematics & Statistics* (In Press.)](https://drive.google.com/file/d/1RFPNQ0ctz2Zea-7nzTEO_7yNASjlMVhE/view?usp=sharing)**



---

## Preprints

**[1. Korley, J. T.* (2025). Robust Survival Estimation under Interval Censoring: Expectation-Maximization and Bayesian Accelerated Failure Time Assessment via Simulation and Application. arXiv preprint arXiv:2508.16894.](https://arxiv.org/html/2509.02634v1)**
<br>
<br>
**[2. Korley, J. T.* (2025). Individualized Treatment Effects in Advanced Prostate Cancer: A Causal-Survival Modeling Approach to Risk-Guided Therapy. arXiv preprint arXiv:2508.16894.](https://arxiv.org/abs/2508.16894)**
<br>
<br>
**[3. Kubuafor, E., Baidoo, D., Okeke, O. J., Amevor, R., Arhin, G., & Korley, J. T.* (2025). Evaluation of Time Series Forecasting Models for Predicting Lung Cancer Mortality Rates in the United States: A Comparison with Altuhaifa (2023) Study. arXiv preprint arXiv:2508.16052.](https://arxiv.org/abs/2508.16052)**

--- 

## Manuscripts In Preparation

**1. Modeling of Physical Activity and its association with cogntive status of AD patients using Novel Quantile and Functional Distributions method-NHATS( 2026)---Manuscript preparation**
<br>
<br>
**2. Electrocardiogram Heart Rate Variability Hidden Markov & Funtional Data Analysis- Research (2026)- Present--Manuscript preparation**
<br>
<br>
**[3.Korley, J.T.* (2025). Covariate-Adjusted Treatment Effects for Recurrent Events with Terminal Outcomes]()**
<br>
<br>
**[4.Korley, J.T.* (2025). Timing of First Neuroimaging in Alzheimer’s Disease: A Competing-Risk Analysis of Genetic, Cognitive,\& Demographic Determinants](https://drive.google.com/file/d/1fRKbwwGjyfJkRiwMm624xTdY8JAIaEnZ/view?usp=sharing)**
<br>
<br>
**5.  Korley, J.T.* \& Adu Bonsu, E. (2025). Bayesian Hierarchical Modeling of Time-to-Dropout in Alzheimer’s Disease Research Cohorts.**
<br>
<br>
**4.Korley, J.T.* (2025). Robust Survival Estimation under Interval Censoring: Expectation-Maximization and Bayesian Accelerated Failure Time Assessment via Simulation and Application.**
<br>
<br>
**6.Korley, J.T.* (2025). Individualized Treatment Effects in Advanced Prostate Cancer: A Survival Modeling Approach to Risk-Guided Therapy.**

---

## New Project- Framework
*High-Dimensional Mediation Analysis with Survival Outcomes*: A Double Machine Learning and Causal Inference Approach.  
    - Development of `JsurvMediateML`, an R package for implementing high-dimensional survival mediation analysis with clinical applications.

---

## Conference Proceedings: Poster Presentations


**[1.Sukanya B. , Korley, J. T.*, Peng Y., Wang R.(2025). Dose-Finding and Missing Data Analysis in a Simulated Phase II Psoriasis Trial. Statistics In Pharceutical-UCONN 2025.](https://events.stat.uconn.edu/SIP2025/posters2025.html)**
<br>
<br>
**[2. Korley, J. T.* (2025). Individualized Treatment Effects in Advanced Prostate Cancer: A Causal-Survival Modeling Approach to Risk-Guided Therapy. Statistics In Pharceutical-UCONN 2025.](https://events.stat.uconn.edu/SIP2025/posters2025.html)**
<br>
<br>
**[3. Korley, J. T.* (2025). Individualized Treatment Effects in Advanced Prostate Cancer: A Causal-Survival Modeling Approach to Risk-Guided Therapy. 2025 Boston Pharmaceutical Symposium, November 8, 2025**
<br>
<br>
**[4. Korley, J. T.* (2026).Timing of Neuroimaging Acquisition in Alzheimer’s Disease. Competing-risk framework integrating APOE ε4 geno-type, cognition, and demographics to examine determinants of first imaging. 7th Big Data Health Conference, February 12, 2026**

